name: simpledb
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    working-directory: simpledb

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: simpledb/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: simpledb # https://github.com/golangci/golangci-lint-action/issues/369#issuecomment-2094494008

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: simpledb/go.mod
      - name: Test
        run: go test ./...
